In [1]:
import numpy as np

In [2]:
x = np.array([0,0,0,0,1,1,1,1])      # original
x_rot = np.roll(x, 1)               # rotated

print(x, x_rot)

X = np.fft.fft(x)
X_rot = np.fft.fft(x_rot)

print(X, '\n', X_rot)
print(np.abs(X), '\n', np.abs(X_rot))
print(np.allclose(np.abs(X), np.abs(X_rot)))  # True

[0 0 0 0 1 1 1 1] [1 0 0 0 0 1 1 1]
[ 4.+0.j         -1.+2.41421356j  0.+0.j         -1.+0.41421356j
  0.+0.j         -1.-0.41421356j  0.+0.j         -1.-2.41421356j] 
 [4.+0.j         1.+2.41421356j 0.+0.j         1.+0.41421356j
 0.+0.j         1.-0.41421356j 0.+0.j         1.-2.41421356j]
[4.         2.61312593 0.         1.0823922  0.         1.0823922
 0.         2.61312593] 
 [4.         2.61312593 0.         1.0823922  0.         1.0823922
 0.         2.61312593]
True


In [3]:
np.fft.ifftn(X)

array([0.00000000e+00+0.j, 0.00000000e+00+0.j, 5.55111512e-17+0.j,
       0.00000000e+00+0.j, 1.00000000e+00+0.j, 1.00000000e+00+0.j,
       1.00000000e+00+0.j, 1.00000000e+00+0.j])

In [4]:
np.fft.ifftn(np.abs(X))

array([ 1.42387953+0.j,  0.77059805+0.j,  0.5       +0.j,  0.22940195+0.j,
       -0.42387953+0.j,  0.22940195+0.j,  0.5       +0.j,  0.77059805+0.j])

In [5]:
a = np.array([0,0,0,0,1,1,1,1])
b = np.array([1,0,0,1,0,1,0,1])

A = np.fft.fft(a)
B = np.fft.fft(b)

print("DFT mag a:", np.round(np.abs(A), 2))
print("DFT mag b:", np.round(np.abs(B), 2))
print("Equal?", np.allclose(np.abs(A), np.abs(B)))

DFT mag a: [4.   2.61 0.   1.08 0.   1.08 0.   2.61]
DFT mag b: [4.   0.77 1.41 1.85 2.   1.85 1.41 0.77]
Equal? False


In [6]:
# Define binary vectors
x = np.array([0, 0, 1, 0, 0, 1, 1, 1])
y = np.array([0, 0, 1, 1, 1, 0, 0, 1])

# Compute FFTs
X = np.fft.fft(x)
Y = np.fft.fft(y)

# Compute magnitudes
mag_X = np.round(np.abs(X), 5)
mag_Y = np.round(np.abs(Y), 5)

# Print results
print("x:", x)
print("y:", y)
print("Magnitude FFT of x:", mag_X)
print("Magnitude FFT of y:", mag_Y)
print("Are magnitudes equal?", np.allclose(mag_X, mag_Y)) # it seems this is good ??

x: [0 0 1 0 0 1 1 1]
y: [0 0 1 1 1 0 0 1]
Magnitude FFT of x: [4.      1.41421 2.      1.41421 0.      1.41421 2.      1.41421]
Magnitude FFT of y: [4.      1.41421 2.      1.41421 0.      1.41421 2.      1.41421]
Are magnitudes equal? True


In [7]:
np.roll(x[::-1], 2) == y

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [8]:
# Define bitstrings
x = np.array([0, 1, 0, 1, 1, 0, 0, 1])
y = np.array([1, 0, 1, 0, 0, 1, 1, 0])
[0,1,1,0,0,1,0,1]

# Compute DFTs
X = np.fft.fft(x)
Y = np.fft.fft(y)

# Compare magnitude spectra
print(X)
print(Y)
print("Magnitude equal? ", np.allclose(np.abs(X), np.abs(Y))) # reflect and rotate gives the same

[ 4.        +0.j         -0.29289322-0.70710678j  1.        +1.j
 -1.70710678-0.70710678j -2.        +0.j         -1.70710678+0.70710678j
  1.        -1.j         -0.29289322+0.70710678j]
[ 4.        +0.j          0.29289322+0.70710678j -1.        -1.j
  1.70710678+0.70710678j  2.        +0.j          1.70710678-0.70710678j
 -1.        +1.j          0.29289322-0.70710678j]
Magnitude equal?  True


In [9]:
x = [0, 0, 1, 0, 0, 1, 1, 1]
y = [0, 0, 0, 1, 1, 0, 1, 1]

# Compute DFTs
X = np.fft.fft(x)
Y = np.fft.fft(y)

# Compare magnitude spectra
print(X)
print(Y)
print("Magnitude equal? ", np.allclose(np.abs(X), np.abs(Y))) 

[ 4.+0.j          0.+1.41421356j -2.+0.j          0.+1.41421356j
  0.+0.j          0.-1.41421356j -2.+0.j          0.-1.41421356j]
[ 4.+0.j -1.+1.j  0.+2.j -1.-1.j  0.+0.j -1.+1.j  0.-2.j -1.-1.j]
Magnitude equal?  True


In [10]:
np.array([1,1,0,1,1,0,0,0])[::-1]

array([0, 0, 0, 1, 1, 0, 1, 1])

In [11]:
0b0001

1

In [12]:
0b1000

8

In [13]:
def find_dft_magnitude_collisions(L):
    """Search all binary strings of length L for DFT-magnitude collisions not related by rotation/reflection."""
    from itertools import product
    all_signals = list(product([0, 1], repeat=L))
    seen = {}
    collisions = []
    
    for x in all_signals:
        x = np.array(x)
        mag = tuple(np.round(np.abs(np.fft.fft(x)), 5))  # Use rounding to avoid tiny FP errors
        
        if mag not in seen:
            seen[mag] = [x]
        else:
            for y in seen[mag]:
                # Check dihedral equivalence
                y_equiv = {
                    tuple(np.roll(y, r)) for r in range(L)
                }.union({
                    tuple(np.roll(y[::-1], r)) for r in range(L)
                }).union({
                    tuple(np.roll(1-y, r)) for r in range(L)
                }).union({
                    tuple(np.roll((1-y)[::-1], r)) for r in range(L)
                })
                if tuple(x) not in y_equiv:
                    collisions.append((x, y))
                    return collisions  # Return first one found (can remove this to get all)
            seen[mag].append(x)
    
    return collisions # this almost works, except there are two strings for N=12 --> N=20 or greater which don't match

In [14]:
find_dft_magnitude_collisions(10)

[]

In [15]:
1- np.array([1, 0, 0])

array([0, 1, 1])

In [16]:
np.logical_not(np.array([1, 0, 0])).astype(int)

array([0, 1, 1])

In [17]:
def autocorrelation(x):
    """
    Compute the circular autocorrelation of +/-1 sequence x.
    x: 1D numpy array of length L with elements +1 or -1.
    Returns: numpy array A of length L, A[k] = sum_j x[j]*x[(j+k)%L].
    """
    L = len(x)
    A = np.zeros(L, dtype=int)
    for k in range(L):
        s = 0
        for j in range(L):
            s += x[j] * x[(j + k) % L]
        A[k] = s
    return A

def walsh_hadamard_transform(x):
    """
    Compute the Walsh-Hadamard transform (WHT) of input vector x.
    Length of x must be a power of two.
    Returns: numpy array of same length as x.
    """
    L = len(x)
    if L == 1:
        return x
    else:
        x = np.array(x)
        if (L & (L - 1)) != 0:
            raise ValueError("Length of input must be a power of two")
        half = L // 2
        top = walsh_hadamard_transform(x[:half])
        bottom = walsh_hadamard_transform(x[half:])
        return np.concatenate([top + bottom, top - bottom])

def auto_wht(bitstring):
    """
    Given a bitstring (list or array of 0/1), compute autocorrelation + WHT.
    Returns: numpy array of WHT of autocorrelation vector.
    """
    # Convert bitstring to +1/-1 sequence
    x = np.array([1 if b == 0 else -1 for b in bitstring])
    A = autocorrelation(x)
    T = walsh_hadamard_transform(A)
    return T

# Example usage
if __name__ == "__main__":
    bitstring = [1, 1, 0, 1, 0, 0, 1, 0]  # length 8 (power of two)
    T = auto_wht(bitstring)
    print("WHT of autocorrelation:", T)

WHT of autocorrelation: [ 0  0  0  0 16 16  0 32]


In [18]:
autocorrelation(bitstring)

array([4, 1, 2, 3, 0, 3, 2, 1])

In [19]:
autocorrelation(bitstring[::-1])

array([4, 1, 2, 3, 0, 3, 2, 1])

In [20]:
walsh_hadamard_transform([0, 1, 0, 1])

array([ 2, -2,  0,  0])

In [21]:
walsh_hadamard_transform([1, -1, 1, -1])

array([0, 4, 0, 0])

In [22]:
def find_auto_wht_magnitude_collisions(L):
    from itertools import product
    all_signals = list(product([0, 1], repeat=L))
    seen = {}
    collisions = []
    
    for x in all_signals:
        x = np.array(x)
        mag = tuple(auto_wht(x))  # Use rounding to avoid tiny FP errors
        
        if mag not in seen:
            seen[mag] = [x]
        else:
            for y in seen[mag]:
                # Check dihedral equivalence
                y_equiv = {
                    tuple(np.roll(y, r)) for r in range(L)
                }.union({
                    tuple(np.roll(y[::-1], r)) for r in range(L)
                }).union({
                    tuple(np.roll(1-y, r)) for r in range(L)
                }).union({
                    tuple(np.roll((1-y)[::-1], r)) for r in range(L)
                })
                if tuple(x) not in y_equiv:
                    collisions.append((x, y))
                    return collisions  # Return first one found (can remove this to get all)
            seen[mag].append(x)
    
    return collisions # this almost works, except there are two strings for N=16 or greater which don't match

In [23]:
find_auto_wht_magnitude_collisions(16)

[(array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1]),
  array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1]))]

In [24]:
auto_wht(np.array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1]))

array([64,  0, 32, 32, 16, 16, 16, 16,  8,  8,  8,  8,  8,  8,  8,  8])

In [25]:
auto_wht(np.array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1]))

array([64,  0, 32, 32, 16, 16, 16, 16,  8,  8,  8,  8,  8,  8,  8,  8])

In [26]:
print(autocorrelation((-1)**np.array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1])))
print(autocorrelation((-1)**np.array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1])))

[16  4  0  4  4  4  0  4  8  4  0  4  4  4  0  4]
[16  4  0  4  4  4  0  4  8  4  0  4  4  4  0  4]


In [3]:
def find_collisions(L, f):
    from itertools import product
    all_signals = list(product([0, 1], repeat=L))
    seen = {}
    collisions = []
    
    for x in all_signals:
        x = np.array(x)
        mag = tuple(f(x))  # Use rounding to avoid tiny FP errors
        
        if mag not in seen:
            seen[mag] = [x]
        else:
            for y in seen[mag]:
                # Check dihedral equivalence
                y_equiv = {
                    tuple(np.roll(y, r)) for r in range(L)
                }.union({
                    tuple(np.roll(y[::-1], r)) for r in range(L)
                }).union({
                    tuple(np.roll(1-y, r)) for r in range(L)
                }).union({
                    tuple(np.roll((1-y)[::-1], r)) for r in range(L)
                })
                if tuple(x) not in y_equiv:
                    collisions.append((x, y))
                    return collisions  # Return first one found (can remove this to get all)
            seen[mag].append(x)
    
    return collisions 

In [28]:
find_collisions(16, walsh_hadamard_transform)

[]

In [29]:
import qutip as qt
qt.gates.hadamard_transform(8)

Quantum object: dims=[[2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2]], shape=(256, 256), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 0.0625  0.0625  0.0625 ...  0.0625  0.0625  0.0625]
 [ 0.0625 -0.0625  0.0625 ... -0.0625  0.0625 -0.0625]
 [ 0.0625  0.0625 -0.0625 ...  0.0625 -0.0625 -0.0625]
 ...
 [ 0.0625 -0.0625  0.0625 ... -0.0625  0.0625 -0.0625]
 [ 0.0625  0.0625 -0.0625 ...  0.0625 -0.0625 -0.0625]
 [ 0.0625 -0.0625 -0.0625 ... -0.0625 -0.0625  0.0625]]

In [30]:
qt.gates.hadamard_transform(3).full() @ np.array([1, 0, 1, 0, 1, 0, 0, 1]).reshape((-1, 1))

array([[ 1.41421356+0.j],
       [ 0.70710678+0.j],
       [ 0.        +0.j],
       [ 0.70710678+0.j],
       [ 0.        +0.j],
       [ 0.70710678+0.j],
       [ 0.        +0.j],
       [-0.70710678+0.j]])

In [31]:
walsh_hadamard_transform(np.array([1, 0, 1, 0, 1, 0, 0, 1]))

array([ 4,  2,  0,  2,  0,  2,  0, -2])

In [32]:
def auto_fft(x):
    return np.abs(np.fft.fft(autocorrelation(x)))

In [33]:
np.abs(auto_fft(np.array([1, 0, 1, 0, 1, 0, 0, 1])))

array([16.        ,  0.58578644,  2.        ,  3.41421356,  4.        ,
        3.41421356,  2.        ,  0.58578644])

In [34]:
find_collisions(16, auto_fft)

[(array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1]),
  array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1]))]

In [35]:
def generate_A_mask(x):
    L = len(x)
    A = []
    for k in range(L):
        A.append(sum(x[j] * x[(j + k) % L] for j in range(L)))
    return A

In [20]:
import libraries.utils as utils
N=8
states = utils.generate_input_torch(N).numpy()
signed_states = (-1) ** states

In [37]:
A_mask = np.array([generate_A_mask(x) for x in states])
A_mask

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [7., 6., 6., ..., 6., 6., 6.],
       [7., 6., 6., ..., 6., 6., 6.],
       [8., 8., 8., ..., 8., 8., 8.]], dtype=float32)

In [38]:
autocor = np.array([autocorrelation(x) for x in signed_states])

In [39]:
autocor * A_mask

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 8.,  0.,  0., ...,  0.,  0.,  0.],
       [ 8.,  0.,  0., ...,  0.,  0.,  0.],
       ...,
       [56., 24., 24., ..., 24., 24., 24.],
       [56., 24., 24., ..., 24., 24., 24.],
       [64., 64., 64., ..., 64., 64., 64.]])

In [40]:
(autocor * A_mask).sum(axis=1, keepdims=True)

array([[  0.],
       [  8.],
       [  8.],
       [ 24.],
       [  8.],
       [ 24.],
       [ 24.],
       [ 40.],
       [  8.],
       [ 24.],
       [ 24.],
       [ 24.],
       [ 24.],
       [ 24.],
       [ 40.],
       [ 48.],
       [  8.],
       [ 32.],
       [ 24.],
       [ 32.],
       [ 24.],
       [ 48.],
       [ 24.],
       [ 24.],
       [ 24.],
       [ 32.],
       [ 24.],
       [ 24.],
       [ 40.],
       [ 24.],
       [ 48.],
       [ 48.],
       [  8.],
       [ 24.],
       [ 32.],
       [ 32.],
       [ 24.],
       [ 40.],
       [ 32.],
       [ 24.],
       [ 24.],
       [ 40.],
       [ 48.],
       [ 24.],
       [ 24.],
       [ 48.],
       [ 24.],
       [ 32.],
       [ 24.],
       [ 32.],
       [ 32.],
       [ 64.],
       [ 24.],
       [ 24.],
       [ 24.],
       [ 40.],
       [ 40.],
       [ 24.],
       [ 24.],
       [ 40.],
       [ 48.],
       [ 32.],
       [ 48.],
       [ 88.],
       [  8.],
       [ 24.],
       [ 2

In [41]:
from numpy.fft import fft

def marshall_sign_from_dft(x):
    """
    Compute the Marshall sign from the DFT of a ±1 spin configuration x.
    Assumes L is even and x has zero magnetization.
    """
    L = len(x)
    k = np.arange(L)
    j_even = np.arange(0, L, 2)

    # Compute DFT of x
    x_dft = fft(x)

    # Compute weight vector for even-position projection
    weight_k = np.sum(np.exp(2j * np.pi * np.outer(j_even, k) / L), axis=0)

    # Sum weighted DFT components
    s_even_complex = (1 / L) * np.dot(x_dft, weight_k)

    # Take real part (imaginary part should be ~0)
    s_even_real = np.real_if_close(s_even_complex, tol=1e3)
    s_rounded = int(np.round(s_even_real))

    # Compute Marshall sign
    sign = (-1) ** ((-s_rounded // 2) % 2)
    return sign, s_rounded

In [21]:
import libraries.j1j2_functions as j1j2
gs8 = j1j2.J1J2_hamiltonian(8, 1, 0).eigenstates()[1][0]
states, signs = utils.get_nonzero_states(8, gs8, 1e-10)

In [43]:
def test_dft_marshall_sign(L):
    results = []
    for bits, true_sign in zip(states, signs):
        x = utils.generate_state_array(bits, N)
        dft_sign, s_reconstructed = marshall_sign_from_dft(x)
        correct = dft_sign == true_sign
        results.append((bits, s_reconstructed, true_sign, dft_sign, correct))
    return results

# Run the test for L = 6
test_dft_marshall_sign(6)

[(15, 2, -1, -1, True),
 (23, 3, 1, 1, True),
 (27, 2, -1, -1, True),
 (29, 3, 1, 1, True),
 (30, 2, -1, -1, True),
 (39, 2, -1, -1, True),
 (43, 1, 1, -1, False),
 (45, 2, -1, -1, True),
 (46, 1, 1, -1, False),
 (51, 2, -1, -1, True),
 (53, 3, 1, 1, True),
 (54, 2, -1, -1, True),
 (57, 2, -1, -1, True),
 (58, 1, 1, -1, False),
 (60, 2, -1, -1, True),
 (71, 3, 1, 1, True),
 (75, 2, -1, -1, True),
 (77, 3, 1, 1, True),
 (78, 2, -1, -1, True),
 (83, 3, 1, 1, True),
 (85, 4, -1, 1, False),
 (86, 3, 1, 1, True),
 (89, 3, 1, 1, True),
 (90, 2, -1, -1, True),
 (92, 3, 1, 1, True),
 (99, 2, -1, -1, True),
 (101, 3, 1, 1, True),
 (102, 2, -1, -1, True),
 (105, 2, -1, -1, True),
 (106, 1, 1, -1, False),
 (108, 2, -1, -1, True),
 (113, 3, 1, 1, True),
 (114, 2, -1, -1, True),
 (116, 3, 1, 1, True),
 (120, 2, -1, -1, True),
 (135, 2, -1, -1, True),
 (139, 1, 1, -1, False),
 (141, 2, -1, -1, True),
 (142, 1, 1, -1, False),
 (147, 2, -1, -1, True),
 (149, 3, 1, 1, True),
 (150, 2, -1, -1, True),
 (

In [44]:
marshall_sign_from_dft(np.array([1,0,1,0,1,0]))

(1, 3)

In [4]:
def embed_fourier(bits, M=32):
    s = np.asarray(bits, dtype=float)
    x = s
    x = 2*s - 1
    # x = x - x.mean()
    n = len(x)
    f = np.arange(1, M+1) / (2*M+2)   # frequencies in (0, 0.5]
    # DTFT magnitudes at chosen frequencies
    i_idx = np.arange(n)
    m = []
    for fk in f:
        w = np.exp(-2j*np.pi*fk*(i_idx))
        m.append(np.abs((x * w).sum()) / n)
    return np.array(m)
def fourier(bits):
    s = np.asarray(bits, dtype=float)
    x = 2 * s - 1
    n = len(x)
    ks = np.arange(n)
    A = []
    for k in ks:
        A.append((x * np.exp(-2j * np.pi * np.arange(n) * k / n) ).sum())
    return np.array(A)

In [5]:
print(embed_fourier([0, 1, 0, 1, 0, 1]))
print(embed_fourier([1, 0, 1, 0, 1, 0]))

[4.70086710e-02 9.05166694e-02 1.27253520e-01 1.54395460e-01
 1.69755378e-01 1.71934808e-01 1.60428784e-01 1.35677093e-01
 9.90585241e-02 5.28280304e-02 9.96455660e-17 5.58160225e-02
 1.10618049e-01 1.60241418e-01 2.00602604e-01 2.27943183e-01
 2.39059930e-01 2.31507746e-01 2.03763539e-01 1.55341315e-01
 8.68514264e-02 2.40548322e-16 1.02472083e-01 2.16907912e-01
 3.38904994e-01 4.63528531e-01 5.85556182e-01 6.99741199e-01
 8.01079713e-01 8.85067671e-01 9.47933448e-01 9.86833450e-01]
[4.70086710e-02 9.05166694e-02 1.27253520e-01 1.54395460e-01
 1.69755378e-01 1.71934808e-01 1.60428784e-01 1.35677093e-01
 9.90585241e-02 5.28280304e-02 9.96455660e-17 5.58160225e-02
 1.10618049e-01 1.60241418e-01 2.00602604e-01 2.27943183e-01
 2.39059930e-01 2.31507746e-01 2.03763539e-01 1.55341315e-01
 8.68514264e-02 2.40548322e-16 1.02472083e-01 2.16907912e-01
 3.38904994e-01 4.63528531e-01 5.85556182e-01 6.99741199e-01
 8.01079713e-01 8.85067671e-01 9.47933448e-01 9.86833450e-01]


In [6]:
print(embed_fourier([1, 1, 1, 0, 1, 0, 0, 0]))
print(embed_fourier([0, 0, 0, 1, 0, 1, 1, 1]))

[0.16438996 0.31576551 0.44230361 0.53444427 0.58573541 0.59336761
 0.55834788 0.48529922 0.38191158 0.25810567 0.125      0.0062091
 0.12533749 0.22416139 0.2971288  0.34176609 0.35874583 0.35161833
 0.32624622 0.29001207 0.25089273 0.21650635 0.19323891 0.18554598
 0.19550387 0.22265467 0.26415596 0.31521066 0.36972106 0.42108617
 0.46304564 0.49046951]
[0.16438996 0.31576551 0.44230361 0.53444427 0.58573541 0.59336761
 0.55834788 0.48529922 0.38191158 0.25810567 0.125      0.0062091
 0.12533749 0.22416139 0.2971288  0.34176609 0.35874583 0.35161833
 0.32624622 0.29001207 0.25089273 0.21650635 0.19323891 0.18554598
 0.19550387 0.22265467 0.26415596 0.31521066 0.36972106 0.42108617
 0.46304564 0.49046951]


In [7]:
print(np.fft.fft([1, 1, 1, 1, 0, 0, 0, 0]))
print(np.fft.fft([0, 1, 1, 1, 1, 0, 0, 0]))

[4.+0.j         1.-2.41421356j 0.+0.j         1.-0.41421356j
 0.+0.j         1.+0.41421356j 0.+0.j         1.+2.41421356j]
[ 4.+0.j         -1.-2.41421356j  0.+0.j         -1.-0.41421356j
  0.+0.j         -1.+0.41421356j  0.+0.j         -1.+2.41421356j]


In [8]:
print(np.fft.fft(2 * np.array([1, 1, 1, 1, 0, 0, 0, 0]) - 1))
print(np.fft.fft(2 * np.array([1, 1, 1, 0, 0, 0, 0, 1]) - 1))

[0.+0.j         2.-4.82842712j 0.+0.j         2.-0.82842712j
 0.+0.j         2.+0.82842712j 0.+0.j         2.+4.82842712j]
[ 0.        +0.j  4.82842712-2.j  0.        +0.j -0.82842712+2.j
  0.        +0.j -0.82842712-2.j  0.        +0.j  4.82842712+2.j]


In [9]:
print(np.fft.fft(2 * np.array([1, 1, 1, 1, 0, 0, 0, 0]) - 1))
print(np.fft.fft(2 * np.array([0, 1, 1, 1, 1, 0, 0, 0]) - 1))

[0.+0.j         2.-4.82842712j 0.+0.j         2.-0.82842712j
 0.+0.j         2.+0.82842712j 0.+0.j         2.+4.82842712j]
[ 0.+0.j         -2.-4.82842712j  0.+0.j         -2.-0.82842712j
  0.+0.j         -2.+0.82842712j  0.+0.j         -2.+4.82842712j]


In [10]:
print(np.fft.fft([0, 1, 1, 1, 1, 0, 0, 0]))
print(fourier([0, 1, 1, 1, 1, 0, 0, 0]))

[ 4.+0.j         -1.-2.41421356j  0.+0.j         -1.-0.41421356j
  0.+0.j         -1.+0.41421356j  0.+0.j         -1.+2.41421356j]
[ 0.00000000e+00+0.00000000e+00j -2.00000000e+00-4.82842712e+00j
  0.00000000e+00+4.89858720e-16j -2.00000000e+00-8.28427125e-01j
  0.00000000e+00+9.79717439e-16j -2.00000000e+00+8.28427125e-01j
  3.55271368e-15+1.46957616e-15j -2.00000000e+00+4.82842712e+00j]


In [11]:
print(embed_fourier([1, 1, 1, 1, 0, 0, 0, 0]))
print(embed_fourier([0, 1, 1, 1, 1, 0, 0, 0]))

[0.18818091 0.36329353 0.51346103 0.6290699  0.70361488 0.73423389
 0.72188186 0.67113045 0.58961909 0.48721893 0.375      0.26411131
 0.16469097 0.0849181  0.03030157 0.00327341 0.00312119 0.02625646
 0.06678033 0.11727591 0.16973403 0.21650635 0.25117882 0.26927002
 0.2686801  0.24984574 0.21559052 0.17069512 0.12124328 0.07382455
 0.03469033 0.00896416]
[0.09547296 0.19225564 0.29017811 0.38676396 0.47728526 0.55550597
 0.61476858 0.64912879 0.65434181 0.62858094 0.57282196 0.49086706
 0.38901811 0.27544234 0.15930132 0.04973322 0.0452154  0.11962318
 0.17063788 0.19931176 0.21125398 0.21650635 0.22671408 0.24841505
 0.27838785 0.30703169 0.32423494 0.32243724 0.29752001 0.24888332
 0.17917662 0.09377063]


In [12]:
mult = 10000 # the mean abs error seems to be linearly prop to the multiplier somewhat but changes from .121 to .118 every 0 added???
print(np.mean(np.abs((embed_fourier([1, 1, 1, 1, 0, 0, 0, 0] * mult) - embed_fourier([0, 1, 1, 1, 1, 0, 0, 0] * mult)))))

1.1876822018265245e-05


In [13]:
print(embed_fourier([1, 1, 1, 0, 0, 0] * 2))
print(embed_fourier([1, 0, 0, 0, 1, 1] * 2))

[1.36137881e-01 2.34153140e-01 2.64692654e-01 2.13865067e-01
 8.62896422e-02 9.61717934e-02 2.99624090e-01 4.85971118e-01
 6.21451236e-01 6.83839270e-01 6.66666667e-01 5.79596064e-01
 4.45060078e-01 2.92185705e-01 1.49646232e-01 3.92632217e-02
 2.81091577e-02 5.35550814e-02 4.79225798e-02 2.73242428e-02
 7.70005824e-03 1.76756509e-16 7.28785200e-03 2.44688744e-02
 4.05762531e-02 4.28298359e-02 2.12024004e-02 2.78806367e-02
 9.98009746e-02 1.82474547e-01 2.59334460e-01 3.13708615e-01]
[4.63319409e-02 8.44726216e-02 1.04084014e-01 9.32803214e-02
 4.21379456e-02 5.28023963e-02 1.85232752e-01 3.38418616e-01
 4.87630264e-01 6.05159354e-01 6.66666667e-01 6.57206731e-01
 5.75314870e-01 4.34011802e-01 2.58360208e-01 8.00936678e-02
 6.94015582e-02 1.66038024e-01 1.98206548e-01 1.68927688e-01
 9.44920626e-02 2.23581264e-16 8.70087795e-02 1.43181164e-01
 1.54550603e-01 1.19041861e-01 4.57535368e-02 4.86297816e-02
 1.45147013e-01 2.27912199e-01 2.87687329e-01 3.22245727e-01]


In [14]:
mult = 100 # the mean abs error seems to be linearly prop to the multiplier (for using 1/0 format)
print(np.mean(np.abs((embed_fourier([1, 1, 1, 0, 0, 0] * mult) - embed_fourier([1, 0, 0, 0, 1, 1] * mult)))))

0.001667201208536901


In [15]:
find_collisions(16, fourier) # seems like no collisions up to N=16 for either fourier or embed fourier

[]

In [16]:
find_collisions(16, lambda x : np.abs(np.fft.fft(x))) # technically has issues but none have half 1s

[(array([0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0]),
  array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1]))]

In [22]:
import libraries.magnetization as mag
mag.count_magnetization(4)


1

In [37]:
tup_to_int([0, 1, 1, 0])

np.int64(6)

In [76]:
def tup_to_int(x):
    x = np.array(x)
    return int((x * (2 ** np.arange(len(x)))).sum())
def check_symmetries(L, f):

    visited = set()
    collisions = set()
    for state in range(2**L):
        if state not in visited and mag.count_magnetization(state) == L//2:
            y = utils.generate_state_1D(state, L)
            y_equiv = {
                tuple(np.roll(y, r)) for r in range(L)
            }.union({
                tuple(np.roll(y[::-1], r)) for r in range(L)
            }).union({
                tuple(np.roll(1-y, r)) for r in range(L)
            }).union({
                tuple(np.roll((1-y)[::-1], r)) for r in range(L)
            })
            visited.update(set(tup_to_int(x) for x in y_equiv))
            y_equiv = list(y_equiv)
            transform = [f(y) for y in y_equiv]
            for i in range(len(transform)):
                if not np.allclose(transform[0], transform[i]):
                    collisions.add((y_equiv[i], y_equiv[0]))

    return collisions

def gen_equiv(N, x):
    y = utils.generate_state_1D(N, x)
    y_equiv = {
        tuple(np.roll(y, r)) for r in range(L)
    }.union({
        tuple(np.roll(y[::-1], r)) for r in range(L)
    }).union({
        tuple(np.roll(1-y, r)) for r in range(L)
    }).union({
        tuple(np.roll((1-y)[::-1], r)) for r in range(L)
    })
    return y_equiv

def check_states(L, gs, threshold = 1e-10):
    visited = set()
    collisions = set()
    for state in range(2**L):
        if state not in visited and mag.count_magnetization(state) == L//2:
            y = utils.generate_state_1D(state, L)
            y_equiv = {
                tuple(np.roll(y, r)) for r in range(L)
            }.union({
                tuple(np.roll(y[::-1], r)) for r in range(L)
            }).union({
                tuple(np.roll(1-y, r)) for r in range(L)
            }).union({
                tuple(np.roll((1-y)[::-1], r)) for r in range(L)
            })
            visited.update(set(tup_to_int(x) for x in y_equiv))
            y_equiv = list(y_equiv)
            for i in range(len(y_equiv)):
                #print(tup_to_int(y_equiv[i]), tup_to_int(y_equiv[0]))
                if abs(abs(gs[tup_to_int(y_equiv[i])][0]) - abs(gs[tup_to_int(y_equiv[0])][0])) >= threshold:
                    collisions.add((y_equiv[i], y_equiv[0]))
    return collisions

In [23]:
check_symmetries(8, embed_fourier)

{((np.float64(0.0),
   np.float64(0.0),
   np.float64(0.0),
   np.float64(1.0),
   np.float64(0.0),
   np.float64(1.0),
   np.float64(1.0),
   np.float64(1.0)),
  (np.float64(0.0),
   np.float64(0.0),
   np.float64(1.0),
   np.float64(0.0),
   np.float64(1.0),
   np.float64(1.0),
   np.float64(1.0),
   np.float64(0.0))),
 ((np.float64(0.0),
   np.float64(0.0),
   np.float64(0.0),
   np.float64(1.0),
   np.float64(1.0),
   np.float64(0.0),
   np.float64(1.0),
   np.float64(1.0)),
  (np.float64(1.0),
   np.float64(0.0),
   np.float64(0.0),
   np.float64(1.0),
   np.float64(1.0),
   np.float64(1.0),
   np.float64(0.0),
   np.float64(0.0))),
 ((np.float64(0.0),
   np.float64(0.0),
   np.float64(0.0),
   np.float64(1.0),
   np.float64(1.0),
   np.float64(1.0),
   np.float64(0.0),
   np.float64(1.0)),
  (np.float64(0.0),
   np.float64(0.0),
   np.float64(1.0),
   np.float64(0.0),
   np.float64(1.0),
   np.float64(1.0),
   np.float64(1.0),
   np.float64(0.0))),
 ((np.float64(0.0),
   np.float

In [24]:
np.abs(np.fft.fft(2 * np.array([1, 1, 1, 0, 0, 0]) - 1))

array([0., 4., 0., 2., 0., 4.])

In [25]:
np.abs(np.fft.fft(2*np.array([1, 1, 0, 0, 0, 1]) - 1))

array([0., 4., 0., 2., 0., 4.])

In [77]:
symms = check_symmetries(16, lambda x : np.abs(np.fft.rfft((-1) ** np.array(x)))) # seems no issues up to N=16
print(len(symms))
symms

0


set()

In [50]:
utils.find_uniques([n for n in range(2**8) if mag.count_magnetization(n) == 4], 8)

{15: 8, 23: 8, 27: 8, 29: 8, 39: 8, 43: 8, 45: 8, 51: 4, 53: 8, 85: 2}

In [51]:
bin(51)

'0b110011'

In [62]:
0b0000011111, 0b1111100000

(31, 992)

In [ ]:
import qutip as qt
L=14
#gs = j1j2.J1J2_hamiltonian(L, 1, 0).eigenstates()[1][0]
gs = qt.qload(f'../J1J2_info/N{L}/n{L}gs_J2_{0.0}')
collisions = check_states(L, gs)
print(len(collisions))
collisions
# NOTE SYMMETRY ONLY MEANS THAT |psi^2| IS THE SAME, THERE COULD BE PHASE DIFFERENT 
# there is no phase difference for N%4=0, but there is for N%4=2

0


set()

: 

In [64]:
gs[31], gs[992]

(array([0.0004815+0.j]), array([-0.0004815-0.j]))

In [112]:
%%timeit
np.fft.fft([1, 0, 1, 0, 1, 1, 0, 0])

4.46 μs ± 53.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [113]:
%%timeit
fourier([1, 0, 1, 0, 1, 1, 0, 0])

37.7 μs ± 1.72 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [267]:
np.fft.fft([1, 0, 1, 0])

array([2.+0.j, 0.+0.j, 2.+0.j, 0.+0.j])

In [114]:
np.histogram(np.abs(np.fft.rfft((-1) ** np.array([1, 0, 0, 1, 1, 0]))))

(array([1, 0, 0, 0, 0, 2, 0, 0, 0, 1]),
 array([0.        , 0.34641016, 0.69282032, 1.03923048, 1.38564065,
        1.73205081, 2.07846097, 2.42487113, 2.77128129, 3.11769145,
        3.46410162]))

In [115]:
np.abs(np.fft.rfft((-1) ** np.array([1, 0, 0, 1, 1, 0])))

array([0.        , 2.        , 3.46410162, 2.        ])

In [126]:
np.abs(np.fft.rfft((-1) ** np.array([0, 0, 1, 1, 1, 0])))

array([0.00000000e+00, 4.00000000e+00, 2.22044605e-16, 2.00000000e+00])

In [122]:
np.abs(np.fft.rfft((-1) ** np.array([1, 1, 1, 1])))

array([4., 0., 0.])

In [125]:
np.abs(np.fft.rfft((-1) ** np.array([1, 0, 1, 0, 1, 0])))

array([0., 0., 0., 6.])

In [129]:
np.fft.rfft([1, -1, 1, -1, -1, 1])

array([0.+0.j        , 2.+0.j        , 0.+3.46410162j, 2.+0.j        ])