In [2]:
import numpy as np
import qutip as qt
import matplotlib.pyplot as plt
import libraries.utils as utils
import libraries.magnetization as mag
import itertools

In [51]:
def dft_mag(x):
    x = (-1) ** np.array(x)
    return np.abs(np.fft.rfft(x)[1:])

def psd(x):
    return dft_mag(x) ** 2
def norm_psd(x):
    vec = psd(x)
    return vec / np.linalg.norm(vec)
# note all the data points have dc component = 0

In [4]:
N=4; J1=1; J2=0
# we have 1100 and 1010 as distinct states

In [5]:
np.fft.fft([1, -1, 1, -1])

array([0.+0.j, 0.+0.j, 4.+0.j, 0.+0.j])

In [48]:
def sign_rule(fft, N):
    # return 1/2 * (1/N * sum(fft[k] * (1 + np.exp(2 * np.pi * 1.j * 2 * k / N)) for k in range(N)) + N/2)
    # return 1/2 * (-1/N * sum(fft[k] * sum(np.exp(2 * np.pi * 1.j * m * k / N) for m in range(0, N, 2)) for k in range(N)) + N/2)
    return 1/4*(-(fft[0] + fft[N//2]) + N)

In [31]:
N=4
sign_rule(np.fft.fft([1, -1, 1, -1]), N)

np.complex128(0j)

In [32]:
sign_rule(np.fft.fft([1, 1, -1, -1]), N)

np.complex128(1+0j)

In [33]:
N=6
# has 000111, 001011, 001101, 101010 as unique

In [34]:
utils.find_uniques([n for n in range(2**N) if mag.count_magnetization(n) == N/2], N)

{7: 6, 11: 6, 13: 6, 21: 2}

In [35]:
sign_rule(np.fft.fft([1, 1, 1, -1, -1, -1]), N)

np.complex128(1-1.1102230246251565e-16j)

In [36]:
sign_rule(np.fft.fft([1, 1, -1, 1, -1, -1]), N)

np.complex128(2-5.551115123125783e-17j)

In [37]:
sign_rule(np.fft.fft([1, -1, -1, 1, -1, 1]), N)

np.complex128(2+5.551115123125783e-17j)

In [38]:
sign_rule(np.fft.fft([1, -1, 1, -1, 1, -1]), N)

np.complex128(0j)

In [15]:
N=100; k = 101
sum(np.exp(2 * np.pi * 1.j * m * k / N) for m in range(N)).round(3) # seems this is satisfied by roots of unity

np.complex128(-0+0j)

In [24]:
N=14
for k in range(N):
    print(sum(np.exp(2 * np.pi * 1.j * m * k / N) for m in range(0, N, 2)).round(3))

(7+0j)
(-0-0j)
(-0+0j)
-0j
0j
0j
0j
(7-0j)
(-0+0j)
(-0+0j)
0j
0j
(-0+0j)
-0j


In [47]:
x = np.fft.fft([1, -1, 1, -1, 1, -1])
1/4 * (-x[6//2] + 6)

np.complex128(0j)

In [53]:
dft_mag([1, 0, 1, 0, 1, 0])

array([0., 0., 6.])

In [65]:
N=10
for x in range(2 ** N):
    state = utils.generate_state_1D(x, N)
    if state.sum() == N//2:
        print(state, np.fft.rfft((-1) ** state).round(2))

[1. 1. 1. 1. 1. 0. 0. 0. 0. 0.] [ 0.+0.j   -2.+6.16j  0.+0.j   -2.+1.45j  0.+0.j   -2.+0.j  ]
[1. 1. 1. 1. 0. 1. 0. 0. 0. 0.] [ 0.  +0.j   -1.62+4.98j -1.38+1.9j   0.62-0.45j -3.62+1.18j  2.  +0.j  ]
[1. 1. 1. 0. 1. 1. 0. 0. 0. 0.] [ 0.  +0.j   -0.62+4.25j -3.62+1.18j  1.62+2.63j -1.38-1.9j  -2.  +0.j  ]
[1. 1. 0. 1. 1. 1. 0. 0. 0. 0.] [ 0.  +0.j    0.62+4.25j -3.62-1.18j -1.62+2.63j -1.38+1.9j   2.  +0.j  ]
[1. 0. 1. 1. 1. 1. 0. 0. 0. 0.] [ 0.  +0.j    1.62+4.98j -1.38-1.9j  -0.62-0.45j -3.62-1.18j -2.  +0.j  ]
[0. 1. 1. 1. 1. 1. 0. 0. 0. 0.] [0.+0.j   2.+6.16j 0.+0.j   2.+1.45j 0.+0.j   2.+0.j  ]
[1. 1. 1. 1. 0. 0. 1. 0. 0. 0.] [ 0.+0.j   -2.+3.8j   0.+3.8j  -2.-2.35j  0.+2.35j -2.+0.j  ]
[1. 1. 1. 0. 1. 0. 1. 0. 0. 0.] [ 0.  +0.j   -1.  +3.08j -2.24+3.08j -1.  +0.73j  2.24-0.73j -6.  +0.j  ]
[1. 1. 0. 1. 1. 0. 1. 0. 0. 0.] [ 0.  +0.j    0.24+3.08j -2.24+0.73j -4.24+0.73j  2.24+3.08j -2.  +0.j  ]
[1. 0. 1. 1. 1. 0. 1. 0. 0. 0.] [ 0.  +0.j    1.24+3.8j   0.  +0.j   -3.24-2.35j  0.  +0

In [ ]:
(-2 + 10)/4, (2+10)/4 # DFT mag erases too much information. we need phase

(2.0, 3.0)