In [ ]:
from libraries.lib import lib
from libraries.NeuralStates import NeuralStates

ImportError: cannot import name 'lib' from 'libraries.lib' (C:\Users\taoha\OneDrive\Documents\GitHub\kans_urop\libraries\lib.py)

In [2]:
from libraries import lib, NeuralStates

In [11]:
lib.calc_bitdist(1, 5, 10)

1

In [5]:
from libraries import lib as p

In [6]:
NeuralStates.SparseStateVector

libraries.NeuralStates.SparseStateVector

In [13]:
from libraries.NeuralStates import *

In [15]:
x = SparseStateVector()
x.values

{}

In [7]:
from test import test_functions

In [8]:
from test import test_functions2

In [9]:
test_functions.test_function(1)

2

In [10]:
test_functions2.test_function2(2)

3

In [9]:
calc_bitdist(1, 5, 3)

1

In [12]:
libraries.lib

NameError: name 'libraries' is not defined

In [11]:
test

NameError: name 'test' is not defined

In [10]:
libraries.lib.TFIM_hamiltonian(2, 1, 1)

NameError: name 'libraries' is not defined

In [2]:
import sys; import os; sys.path.insert(0, os.path.abspath('..'))
sys.path.insert(0, os.path.abspath('../..'))
# import lib
# from NeuralStates import *

In [12]:
x = __import__("kans-urop")

ModuleNotFoundError: No module named 'kans-urop'

In [13]:
os.path.abspath('..')

'c:\\Users\\taoha\\OneDrive\\Documents\\GitHub\\kans_urop'

In [14]:
sys.path

['c:\\Users\\taoha\\OneDrive\\Documents\\GitHub',
 'c:\\Users\\taoha\\OneDrive\\Documents\\GitHub\\kans_urop',
 'c:\\Users\\taoha\\OneDrive\\Documents\\GitHub',
 'c:\\Users\\taoha\\OneDrive\\Documents\\GitHub\\kans_urop',
 'c:\\Users\\taoha\\anaconda3\\envs\\kans\\python312.zip',
 'c:\\Users\\taoha\\anaconda3\\envs\\kans\\DLLs',
 'c:\\Users\\taoha\\anaconda3\\envs\\kans\\Lib',
 'c:\\Users\\taoha\\anaconda3\\envs\\kans',
 '',
 'c:\\Users\\taoha\\anaconda3\\envs\\kans\\Lib\\site-packages',
 'c:\\Users\\taoha\\anaconda3\\envs\\kans\\Lib\\site-packages\\win32',
 'c:\\Users\\taoha\\anaconda3\\envs\\kans\\Lib\\site-packages\\win32\\lib',
 'c:\\Users\\taoha\\anaconda3\\envs\\kans\\Lib\\site-packages\\Pythonwin']

In [15]:
help(x)

NameError: name 'x' is not defined

In [16]:
import kans_urop

In [17]:
help(kans_urop)

Help on package kans_urop:

NAME
    kans_urop

PACKAGE CONTENTS
    NeuralStates
    lib
    test (package)

FILE
    c:\users\taoha\onedrive\documents\github\kans_urop\__init__.py




In [9]:
from kans_urop.NeuralStates import *

In [10]:
lib.TFIM_hamiltonian(1, 1, 1)

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=True
Qobj data =
[[-1. -1.]
 [-1. -1.]]

In [11]:
SparseStateVector().values

{}

In [12]:
print(lib)

<module 'lib' from 'c:\\Users\\taoha\\OneDrive\\Documents\\GitHub\\kans_urop\\lib.py'>


In [13]:
print(type(lib))

<class 'module'>


In [14]:
help(lib)

Help on module lib:

NAME
    lib

FUNCTIONS
    TFIM_expectation_from_array(psi, N, J, Gamma)
        Calculates <psi|H|psi>/<psi|psi>

    TFIM_expectation_from_torch(nn_output, vars, output_to_psi)
        Args:
            nn_output: torch.tensor of shape (2^N, N) output from torch model
            vars: tuple of (N, J, Gamma)
            output_to_psi: function converting nn_output to 2^N size
            statevector

    TFIM_expectation_using_locals(sampled_vector, N, J, Gamma, model, output_to_psi)

    TFIM_hamiltonian(N, J, gamma)
        Generates sparse Qobj for TFIM system with ring shape

    TFIM_multiply(psi, phi, N, J, Gamma)
        Outputs H|psi> into vector phi

        Args:
            psi: 1D array representing statevector
            phi: 1D array to output results to
            N, J, Gamma: parameters in Hamiltonian

    calc_H_elem(N, J, Gamma, i, j)
        Calculates <i|H|j>

    calc_bitdist(a, b, N)

    compute_NN_manual(weights, layers, N, J, Gamma)
  

In [18]:
import kans_urop.test

In [20]:
kans_urop.test.test_function(1)

AttributeError: module 'kans_urop.test' has no attribute 'test_function'

In [ ]:
from kans_urop import *

In [4]:
lib.TFIM_hamiltonian(2, 1, 1)

NameError: name 'lib' is not defined

In [6]:
test.test_functions

NameError: name 'test' is not defined

In [3]:
import kans_urop

In [4]:
help(kans_urop)

Help on package kans_urop:

NAME
    kans_urop

PACKAGE CONTENTS
    NeuralStates
    lib
    test (package)

FILE
    c:\users\taoha\onedrive\documents\github\kans_urop\__init__.py




In [6]:
lib.TFIM_hamoltonian(2, 1, 1)

NameError: name 'lib' is not defined

In [8]:
import kans_urop.lib

In [10]:
kans_urop.lib.TFIM_hamiltonian(2, 1, 1)

Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[-2. -1. -1.  0.]
 [-1.  2.  0. -1.]
 [-1.  0.  2. -1.]
 [ 0. -1. -1. -2.]]