In [1]:
import qutip as qt
import numpy as np

In [2]:
# J1-J2 system, H = J1 * sum Si dot S(i + 1) + J2 * sum Si dot S(i+2)

In [3]:
# define hamiltonian
def TFIM_hamiltonian(n, J, gamma):
    # uses ring shape
    id = qt.qeye(2)
    z = qt.sigmaz()
    x = qt.sigmax()
    sxi = []
    szi = []
    for i in range(n):
        sxi.append(qt.tensor([id] * i + [x] + [id] * (n - i - 1)))
        szi.append(qt.tensor([id] * i + [z] + [id] * (n - i - 1)))
    return J * sum(szi[i] * szi[i + 1] for i in range(n - 1)) - szi[n - 1] * szi[0] - gamma * sum(sxi[i] for i in range(n))

In [4]:
x = qt.rand_ket(4)
y = qt.rand_ket(4)

In [5]:
x.dag() * y

(0.15860163929443533+0.006877348851570417j)

In [6]:
x.dag() @ y

(0.15860163929443533+0.006877348851570417j)

In [7]:
def J1J2_hamiltonian(N, j1, j2):
    id = qt.qeye(2)
    x = qt.sigmax()
    y = qt.sigmay()
    z = qt.sigmaz()
    sxi = []; syi = []; szi = []
    for i in range(N):
        sxi.append(qt.tensor([id] * i + [x] + [id] * (N - i - 1)))
        syi.append(qt.tensor([id] * i + [y] + [id] * (N - i - 1)))
        szi.append(qt.tensor([id] * i + [z] + [id] * (N - i - 1)))
    sis = [sxi, syi, szi]
    J1_term = j1 * (sum(sis[coord][i] * sis[coord][i + 1] for coord in range(len(sis)) for i in range(N - 1)) + sum(sis[coord][N - 1] * sis[coord][0] for coord in range(len(sis))))
    J2_term = j2 * (sum(sis[coord][i] * sis[coord][i + 2] for coord in range(len(sis)) for i in range(N - 2)) + sum(sis[coord][N - 2] * sis[coord][0] for coord in range(len(sis))) + sum(sis[coord][N - 1] * sis[coord][1] for coord in range(len(sis))))
    return J1_term + J2_term


In [8]:
J1J2_hamiltonian(2, 1, 0).eigenstates()

(array([-6.,  2.,  2.,  2.]),
 array([Quantum object: dims=[[2, 2], [1, 1]], shape=(4, 1), type='ket', dtype=Dense
        Qobj data =
        [[ 0.        ]
         [ 0.70710678]
         [-0.70710678]
         [ 0.        ]]                                                             ,
        Quantum object: dims=[[2, 2], [1, 1]], shape=(4, 1), type='ket', dtype=Dense
        Qobj data =
        [[1.]
         [0.]
         [0.]
         [0.]]                                                                      ,
        Quantum object: dims=[[2, 2], [1, 1]], shape=(4, 1), type='ket', dtype=Dense
        Qobj data =
        [[0.        ]
         [0.70710678]
         [0.70710678]
         [0.        ]]                                                              ,
        Quantum object: dims=[[2, 2], [1, 1]], shape=(4, 1), type='ket', dtype=Dense
        Qobj data =
        [[0.]
         [0.]
         [0.]
         [1.]]                                                           

In [9]:
eigs4 = J1J2_hamiltonian(4, 1, 0).eigenstates()
print(eigs4[0][0])

-7.999999999999984


In [10]:
for i in range(16):
    print(bin(i), round(eigs4[1][0][i][0].real, 5))

0b0 0.0
0b1 0.0
0b10 0.0
0b11 0.28868
0b100 0.0
0b101 -0.57735
0b110 0.28868
0b111 0.0
0b1000 0.0
0b1001 0.28868
0b1010 -0.57735
0b1011 0.0
0b1100 0.28868
0b1101 0.0
0b1110 0.0
0b1111 0.0


In [11]:
eigs10 = J1J2_hamiltonian(10, 1, 0).eigenstates()
print(eigs10[0][0])

-18.06178541796817


In [12]:
for i in range(1024):
    print(bin(i), round(eigs10[1][0][i][0].real, 5))

0b0 0.0
0b1 0.0
0b10 -0.0
0b11 -0.0
0b100 -0.0
0b101 0.0
0b110 -0.0
0b111 0.0
0b1000 -0.0
0b1001 -0.0
0b1010 0.0
0b1011 0.0
0b1100 -0.0
0b1101 0.0
0b1110 0.0
0b1111 -0.0
0b10000 -0.0
0b10001 -0.0
0b10010 -0.0
0b10011 -0.0
0b10100 -0.0
0b10101 0.0
0b10110 -0.0
0b10111 0.0
0b11000 -0.0
0b11001 -0.0
0b11010 0.0
0b11011 -0.0
0b11100 0.0
0b11101 -0.0
0b11110 0.0
0b11111 0.00048
0b100000 -0.0
0b100001 -0.0
0b100010 0.0
0b100011 -0.0
0b100100 0.0
0b100101 -0.0
0b100110 0.0
0b100111 -0.0
0b101000 0.0
0b101001 0.0
0b101010 -0.0
0b101011 0.0
0b101100 0.0
0b101101 0.0
0b101110 -0.0
0b101111 -0.0029
0b110000 0.0
0b110001 -0.0
0b110010 0.0
0b110011 -0.0
0b110100 0.0
0b110101 0.0
0b110110 -0.0
0b110111 0.00637
0b111000 -0.0
0b111001 -0.0
0b111010 0.0
0b111011 -0.00637
0b111100 -0.0
0b111101 0.0029
0b111110 -0.00048
0b111111 -0.0
0b1000000 0.0
0b1000001 -0.0
0b1000010 -0.0
0b1000011 -0.0
0b1000100 0.0
0b1000101 -0.0
0b1000110 0.0
0b1000111 0.0
0b1001000 0.0
0b1001001 -0.0
0b1001010 0.0
0b1001011 -0.0

In [13]:
J1J2_hamiltonian(2, 1, 0)

Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[ 2.  0.  0.  0.]
 [ 0. -2.  4.  0.]
 [ 0.  4. -2.  0.]
 [ 0.  0.  0.  2.]]

In [36]:
J1J2_hamiltonian(2, 1, 0).eigenstates()

(array([-6.,  2.,  2.,  2.]),
 array([Quantum object: dims=[[2, 2], [1, 1]], shape=(4, 1), type='ket', dtype=Dense
        Qobj data =
        [[ 0.        ]
         [ 0.70710678]
         [-0.70710678]
         [ 0.        ]]                                                             ,
        Quantum object: dims=[[2, 2], [1, 1]], shape=(4, 1), type='ket', dtype=Dense
        Qobj data =
        [[1.]
         [0.]
         [0.]
         [0.]]                                                                      ,
        Quantum object: dims=[[2, 2], [1, 1]], shape=(4, 1), type='ket', dtype=Dense
        Qobj data =
        [[0.        ]
         [0.70710678]
         [0.70710678]
         [0.        ]]                                                              ,
        Quantum object: dims=[[2, 2], [1, 1]], shape=(4, 1), type='ket', dtype=Dense
        Qobj data =
        [[0.]
         [0.]
         [0.]
         [1.]]                                                           

In [15]:
def j1j2_hamiltonian(N, J1=1.0, J2=0.5, periodic=False):
    """
    Construct the J1-J2 Heisenberg Hamiltonian for a spin-1/2 chain using QuTiP.
    
    Args:
        N         : number of sites
        J1        : nearest-neighbor coupling
        J2        : next-nearest-neighbor coupling
        periodic  : whether to use periodic boundary conditions
    
    Returns:
        Qobj: the Hamiltonian as a QuTiP Qobj
    """
    sx = qt.sigmax()
    sy = qt.sigmay()
    sz = qt.sigmaz()
    I = qt.qeye(2)

    def interaction(op1, op2, i, j):
        """Two-site interaction between op1 at i and op2 at j."""
        op_list = [I] * N
        op_list[i] = op1
        op_list[j] = op2
        return qt.tensor(op_list)

    H = 0

    # Nearest-neighbor terms (J1)
    for i in range(N - 1 + int(periodic)):
        j = (i + 1) % N
        H += J1 * (
            interaction(sx, sx, i, j) +
            interaction(sy, sy, i, j) +
            interaction(sz, sz, i, j)
        )

    # Next-nearest-neighbor terms (J2)
    for i in range(N - 2 + int(periodic) * 2):
        j = (i + 2) % N
        H += J2 * (
            interaction(sx, sx, i, j) +
            interaction(sy, sy, i, j) +
            interaction(sz, sz, i, j)
        )

    return H

In [43]:
j1j2_hamiltonian(10, 1, 0, periodic = False)

Quantum object: dims=[[2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]], shape=(1024, 1024), type='oper', dtype=CSR, isherm=True
Qobj data =
[[9. 0. 0. ... 0. 0. 0.]
 [0. 7. 2. ... 0. 0. 0.]
 [0. 2. 5. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 5. 2. 0.]
 [0. 0. 0. ... 2. 7. 0.]
 [0. 0. 0. ... 0. 0. 9.]]

In [44]:
eig10_np = j1j2_hamiltonian(10, 1, 0, periodic = False).eigenstates()
print(eig10_np[0][0])

-17.03214082913153


In [45]:
for i in range(1024):
    print(bin(i), eig10_np[1][0][i][0])

0b0 0j
0b1 0j
0b10 0j
0b11 (-4.972177386806655e-18+0j)
0b100 0j
0b101 (2.5639816777020448e-17+0j)
0b110 (-1.590421972773283e-17+0j)
0b111 (6.555248136725501e-18+0j)
0b1000 0j
0b1001 (8.854656038033469e-18+0j)
0b1010 (7.503323237834423e-18+0j)
0b1011 (3.6075999867730765e-33+0j)
0b1100 (4.810968474022027e-17+0j)
0b1101 (1.0580524442348741e-17+0j)
0b1110 (1.4094635094220578e-17+0j)
0b1111 (1.199959525372884e-17+0j)
0b10000 (-1.3363354663099366e-33+0j)
0b10001 (-8.64050453042779e-17+0j)
0b10010 (-7.451979534110776e-18+0j)
0b10011 (-1.7135772579074264e-17+0j)
0b10100 (1.9437234994494913e-17+0j)
0b10101 (-1.6772483409950676e-18+0j)
0b10110 (2.2647374457703612e-18+0j)
0b10111 (4.4130373331657875e-18+0j)
0b11000 (2.314972922227404e-18+0j)
0b11001 (-8.979661207354898e-18+0j)
0b11010 (-1.6033949887203077e-17+0j)
0b11011 (-1.6034678320625296e-18+0j)
0b11100 (4.368898713442557e-19+0j)
0b11101 (-7.462662804331754e-18+0j)
0b11110 (7.933482017718306e-18+0j)
0b11111 (9.515732895235979e-07+0j)
0b100000

In [39]:
J1J2_hamiltonian(2, 1, 0.5)

Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[5. 0. 0. 0.]
 [0. 1. 4. 0.]
 [0. 4. 1. 0.]
 [0. 0. 0. 5.]]