In [3]:
import qutip as qt
import numpy as np

In [4]:
def J1J2_hamiltonian(N, j1, j2):
    id = qt.qeye(2)
    x = qt.sigmax()
    y = qt.sigmay()
    z = qt.sigmaz()
    sxi = []; syi = []; szi = []
    for i in range(N):
        sxi.append(qt.tensor([id] * i + [x] + [id] * (N - i - 1)))
        syi.append(qt.tensor([id] * i + [y] + [id] * (N - i - 1)))
        szi.append(qt.tensor([id] * i + [z] + [id] * (N - i - 1)))
    sis = [sxi, syi, szi]
    J1_term = j1 * (sum(sis[coord][i] * sis[coord][i + 1] for coord in range(len(sis)) for i in range(N - 1)) + sum(sis[coord][N - 1] * sis[coord][0] for coord in range(len(sis))))
    J2_term = j2 * (sum(sis[coord][i] * sis[coord][i + 2] for coord in range(len(sis)) for i in range(N - 2)) + sum(sis[coord][N - 2] * sis[coord][0] for coord in range(len(sis))) + sum(sis[coord][N - 1] * sis[coord][1] for coord in range(len(sis))))
    return J1_term + J2_term

In [5]:
J1 = 1; J2 = 0.5

In [26]:
J1J2_hamiltonian(6, J1, J2).eigenstates()

(array([-9.00000000e+00, -9.00000000e+00, -7.00000000e+00, -7.00000000e+00,
        -7.00000000e+00, -6.27491722e+00, -6.27491722e+00, -6.27491722e+00,
        -6.27491722e+00, -6.27491722e+00, -6.27491722e+00, -5.00000000e+00,
        -5.00000000e+00, -4.00000000e+00, -4.00000000e+00, -4.00000000e+00,
        -4.00000000e+00, -4.00000000e+00, -4.00000000e+00, -1.00000000e+00,
        -1.00000000e+00, -1.00000000e+00, -1.00000000e+00, -1.00000000e+00,
        -1.00000000e+00, -1.33431039e-14, -1.09552879e-14, -8.38736674e-15,
        -5.47058516e-15, -4.47688597e-15, -7.30838347e-16, -3.64032313e-16,
         2.94849333e-15,  3.57153156e-15,  7.31070219e-15,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  1.27491722e+00,  1.27491722e+00,  1.27491722e+00,
         1.27491722e+00,  1.27491722e+00,  1.27491722e+00,  4.00000000e+00,
         4.00000000e+00,  4.00000000e+00,  4.00000000e+00,  4.00000000e+00,
         4.0

In [29]:
gs4 = J1J2_hamiltonian(4, J1, J2).eigenstates()[1][1].full()

In [30]:
for i in range(2 ** 4):
    print(round(gs4[i][0], 3))

0j
0j
(-0+0j)
0j
(-0+0j)
(0.5+0j)
(-0.5+0j)
0j
0j
(-0.5+0j)
(0.5+0j)
(-0+0j)
0j
(-0+0j)
(-0+0j)
0j


C:\Users\taoha\AppData\Local\Temp\ipykernel_29972\1968727228.py:2: DeprecationWarning: The Python built-in `round` is deprecated for complex scalars, and will raise a `TypeError` in a future release. Use `np.round` or `scalar.round` instead.
  print(round(gs4[i][0], 3))


In [54]:
def MG_GS(N):
    """
    N must be even
    """
    dimers = [1/np.sqrt(2) * qt.Qobj([[0], [1], [-1], [0]])] * (N // 2)
    gs = qt.tensor(dimers)
    gs.dims = [[2] * N, [1] * N]
    return gs

In [55]:
J1J2_hamiltonian(4, 1, 0.5).eigenstates()

(array([-6., -6., -2., -2., -2., -2., -2., -2., -2., -2., -2.,  6.,  6.,
         6.,  6.,  6.]),
 array([Quantum object: dims=[[2, 2, 2, 2], [1, 1, 1, 1]], shape=(16, 1), type='ket', dtype=Dense
        Qobj data =
        [[ 0.00000000e+00]
         [ 0.00000000e+00]
         [ 1.28197512e-16]
         [ 5.77350269e-01]
         [-8.58760498e-18]
         [-2.88675135e-01]
         [-2.88675135e-01]
         [ 0.00000000e+00]
         [-1.19609907e-16]
         [-2.88675135e-01]
         [-2.88675135e-01]
         [ 0.00000000e+00]
         [ 5.77350269e-01]
         [ 0.00000000e+00]
         [ 0.00000000e+00]
         [ 0.00000000e+00]]                                                                      ,
        Quantum object: dims=[[2, 2, 2, 2], [1, 1, 1, 1]], shape=(16, 1), type='ket', dtype=Dense
        Qobj data =
        [[ 0.00000000e+00]
         [ 0.00000000e+00]
         [-1.55538745e-31]
         [ 1.97215226e-31]
         [-9.65048947e-16]
         [ 5.00000000e-01]


In [56]:
gs4 = J1J2_hamiltonian(4, 1, 0.5).eigenstates()[1][0]
gs4.dag() @ J1J2_hamiltonian(4, 1, 0.5) @ gs4

(-6.000000000000002+0j)

In [57]:
gs4

Quantum object: dims=[[2, 2, 2, 2], [1, 1, 1, 1]], shape=(16, 1), type='ket', dtype=Dense
Qobj data =
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 1.28197512e-16]
 [ 5.77350269e-01]
 [-8.58760498e-18]
 [-2.88675135e-01]
 [-2.88675135e-01]
 [ 0.00000000e+00]
 [-1.19609907e-16]
 [-2.88675135e-01]
 [-2.88675135e-01]
 [ 0.00000000e+00]
 [ 5.77350269e-01]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]

In [58]:
MG_GS(4)

Quantum object: dims=[[2, 2, 2, 2], [1, 1, 1, 1]], shape=(16, 1), type='ket', dtype=Dense
Qobj data =
[[ 0. ]
 [ 0. ]
 [-0. ]
 [ 0. ]
 [ 0. ]
 [ 0.5]
 [-0.5]
 [ 0. ]
 [-0. ]
 [-0.5]
 [ 0.5]
 [-0. ]
 [ 0. ]
 [ 0. ]
 [-0. ]
 [ 0. ]]

In [59]:
for N in [2, 4, 6, 8, 10]:
    print(N)
    h = J1J2_hamiltonian(N, 1, 0.5)
    gs = MG_GS(N)
    print(f'true {h.eigenstates()[0][0]}')
    print(f'MG {gs.dag() @ h @ gs}')

2
true -2.9999999999999956
MG (-2.9999999999999996+0j)
4
true -5.999999999999988
MG (-5.999999999999997+0j)
6
true -9.000000000000004
MG (-8.999999999999998+0j)
8
true -12.0
MG (-11.999999999999996+0j)
10
true -15.000000000000004
MG (-14.999999999999995+0j)


In [39]:
MG_GS(4)

Quantum object: dims=[[4, 4], [1, 1]], shape=(16, 1), type='ket', dtype=Dense
Qobj data =
[[ 0. ]
 [ 0. ]
 [-0. ]
 [ 0. ]
 [ 0. ]
 [ 0.5]
 [-0.5]
 [ 0. ]
 [-0. ]
 [-0.5]
 [ 0.5]
 [-0. ]
 [ 0. ]
 [ 0. ]
 [-0. ]
 [ 0. ]]

In [66]:
J1J2_hamiltonian(5, 1, 0).eigenstates()

(array([-7.47213595, -7.47213595, -7.47213595, -7.47213595, -3.        ,
        -3.        , -2.23606798, -2.23606798, -2.23606798, -2.23606798,
        -2.23606798, -2.23606798, -2.23606798, -2.23606798,  1.47213595,
         1.47213595,  1.47213595,  1.47213595,  2.23606798,  2.23606798,
         2.23606798,  2.23606798,  2.23606798,  2.23606798,  2.23606798,
         2.23606798,  5.        ,  5.        ,  5.        ,  5.        ,
         5.        ,  5.        ]),
 array([Quantum object: dims=[[2, 2, 2, 2, 2], [1, 1, 1, 1, 1]], shape=(32, 1), type='ket', dtype=Dense
        Qobj data =
        [[ 0.00000000e+00]
         [ 0.00000000e+00]
         [ 3.31909295e-17]
         [-7.37256624e-07]
         [ 1.64555208e-17]
         [-4.68372775e-03]
         [ 2.89544020e-03]
         [ 3.47548472e-02]
         [-1.64557326e-17]
         [ 7.58036085e-03]
         [-7.58155376e-03]
         [-4.16713732e-01]
         [ 1.79021771e-03]
         [ 5.83267610e-01]
         [-2.01308726e-0